---
- name: Setup nginx.conf
  template:
    src: nginx.conf.j2
    dest: "{{ DIR_CONF }}/nginx.conf"
    owner: nginx
    group: nginx
    mode: 0644
  notify: "{{ NAME_SERVICE }} restarted {{ NAME_DAEMON }}"
