---
- name: include_vars for OS
  include_vars: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"

- include: install.yml

- name: Daemon Started
  include_role:
    name: common_tasks
    tasks_from: service_started_{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml

- include_role:
    name: common_tasks
    tasks_from: flush_handlers.yml

- include: setup.yml
