---
- name: www
  hosts: www
  user: root
  roles:
    - systemd
    # - os
    # - common
    # - logrotated
    # - cron
    # - openssh
    # - docker
    # - docker-compose
    # - mackerel-agent
