---
- name: www
  hosts: www
  user: root
  roles:
    - systemd
    - os
    - common
    - sysstat
    - logrotate
    - cron
    - openssh
    # - docker
    # - docker-compose
    # - mackerel-agent
