---
- name: www
  hosts: www
  user: root
  roles:
    - middlewares/systemd
    - os
    - common
    - sysstat
    - logrotate
    - cron
    - sshd
    - docker
    - docker-compose
    - mackerel-agent
