---
- name: www
  hosts: www
  user: root
  roles:
    - systemd
    - common
    - os
    - iptables
    - sysstat
    - logrotate
    - cron
    - openssh
    - docker
    - docker-compose
    - mackerel-agent
