---
- name: Setup Systemd
  template:
    src: systemd.conf.j2
    dest: /etc/systemd/systemd.conf
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: "{{ NAME_SERVICE }} restarted systemd"
  when:
    - SYSTEMD_SETTINGS is defined
    - ansible_virtualization_type != 'docker'

- include_role:
    name: common_tasks
    tasks_from: flush_handlers.yml
