---
- name: Remove cronie-anacron
  yum:
    name: cronie-anacron
    state: discard
  when: not ansible_check_mode

- name: Install cronie-noanacron
  yum:
    name: cronie-noanacron
    state: installed
