---
- name: Setup Cron Tab
  cron:
    name: "{{ item.NAME }}"
    minute: "{{ item.MINUTE | default('*') }}"
    hour: "{{ item.HOUR | default('*') }}"
    day: "{{ item.DAY | default('*') }}"
    month: "{{  item.MONTH | default('*') }}"
    weekday: "{{ item.WEEKDAY | default('*') }}"
    job: "{{ item.JOB }}"
    env: "{{ item.ENV | default('no') }}"
  with_items:
    - "{{ COMMON_CRON_SETTINGS | default([]) }}"
    - "{{ COMMON_HOSTGROUP_CRON_SETTINGS | default([]) }}"
    - "{{ INVENTORY_CRON_SETTINGS | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_CRON_SETTINGS | default([]) }}"
  when:
    - not ansible_check_mode
