---
- name: Setup Config
  template:
    src: "logrotate.conf_{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.j2"
    dest: "/etc/logrotate.conf"
    owner: 'root'
    group: 'root'
    mode: '0644'
