---
- name: Setup Logrotate.conf
  template:
    src: "logrotate.conf.{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.j2"
    dest: "/etc/logrotate.conf"
    owner: 0
    group: 0
    mode: 0644
