---
- name: Service started {{ NAME_DAEMON }}
  service:
    name: "{{ NAME_DAEMON }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != 'docker'

- name: Service restarted {{ NAME_DAEMON }}
  service:
    name: "{{ NAME_DAEMON }}"
    state: restarted
  when:
    - ansible_virtualization_type != 'docker'

- name: Service reloaded {{ NAME_DAEMON }}
  service:
    name: "{{ NAME_DAEMON }}"
    state: reloaded

- name: Service stopped {{ NAME_DAEMON }}
  service:
    name: "{{ NAME_DAEMON }}"
    state: stopped
    enabled: no

- name: Systemd started {{ NAME_DAEMON }}
  systemd:
    name: "{{ NAME_DAEMON }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != 'docker'

- name: Systemd restarted {{ NAME_DAEMON }}
  systemd:
    name: "{{ NAME_DAEMON }}"
    state: restarted
  when:
    - ansible_virtualization_type != 'docker'

- name: Systemd reloaded {{ NAME_DAEMON }}
  systemd:
    name: "{{ NAME_DAEMON }}"
    state: reloaded

- name: Systemd stopped {{ NAME_DAEMON }}
  systemd:
    name: "{{ NAME_DAEMON }}"
    state: stopped
    enabled: no

- name: Systemd relaod daemon
  systemd:
    daemon-reexec: yes
  when: ansible_virtualization_type != 'docker'
  listen: "Systemd reload and restarted docker"

- name: Systemd restarted after reload {{ NAME_DAEMON }}
  systemd:
    name: "{{ NAME_DAEMON }}"
    state: restarted
  listen: "Systemd reload and restarted docker"
