---
- name: Set Repository
  template:
    src: gitlab_gitlab-ce.repo.j2
    dest: /etc/yum.repos.d/gitlab_gitlab-ce.repo
    owner: root
    group: root
    mode: 0644

- name: Install
  yum:
    name: "gitlab-ce-{{ VERSION_GITLAB }}"
