---
- name: Update check yum
  shell: yum check-update
  failed_when: false
  changed_when: false
  register: status_check_update

- name: Update yum
  yum:
    name: '*'
    state: latest
  when:
    - not ansible_check_mode
    - status_check_update.rc != 0
