---
- name: Install python module for SELinux
  yum:
    name: libselinux-python
    state: installed

- name: Disabled Selinux
  selinux:
    state: disabled
  when: selinux_status.stdout == 'Enforcing'
  become: True
  notify: Rebooted

- include_role:
    name: common_tasks
    tasks_from: flush_handlers.yml
