---
- name: Setup hosts.allow
  template:
    src: hosts.allow.j2
    dest: /etc/hosts.allow
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: COMMON_HOSTS_ALLOW_SETTINGS is defined or COMMON_HOSTGROUP_HOSTS_ALLOW_SETTINGS is defined or INVENTORY_HOSTS_ALLOW_SETTINGS is defined or INVENTORY_HOSTGROUP_HOSTS_ALLOW_SETTINGS is defined

- name: Setup hosts.deny
  template:
    src: hosts.deny.j2
    dest: /etc/hosts.deny
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: COMMON_HOSTS_DENY_SETTINGS is defined or COMMON_HOSTGROUP_HOSTS_DENY_SETTINGS is defined or INVENTORY_HOSTS_DENY_SETTINGS is defined or INVENTORY_HOSTGROUP_HOSTS_DENY_SETTINGS is defined
