---
- name: Set SSL Cert
  copy:
    src: "{{ item }}"
    dest: /usr/share/pki/ca-trust-source/anchors/{{ item }}
    owner: 'root'
    group: 'root'
    mode: '0400'
  notify: Update Server Certs
  with_items: "{{ OS_SETTINGS.CA_FILES | default([]) }}"

- import_role:
    name: libraries
    tasks_from: flush_handlers.yml
