---
- name: Install python module for SELinux
  yum:
    name: libselinux-python
    state: installed

- name: Get Status selinux
  shell: getenforce
  register: status_selinux
  failed_when: False
  changed_when: False
  when: not ansible_check_mode

- name: Disabled Selinux
  selinux:
    state: disabled
  when:
    - not ansible_check_mode
    - status_selinux.stdout == 'Enforcing'
  become: True
  notify: Rebooted

- include_role:
    name: common_tasks
    tasks_from: flush_handlers.yml
