---
- name: Install python module for SELinux
  yum:
    name: "{{ ( (ansible_facts.distribution_major_version | int) < 8) | ternary('libselinux-python','python3-libselinux') }}"
    state: installed

- name: Get SELinux Status
  shell: getenforce
  register: status_selinux
  changed_when: False
  failed_when: False
  become: True

- name: Disabled Selinux
  selinux:
    state: disabled
  become: True
  notify: Rebooted
  when:
    - not ansible_check_mode
    - status_selinux.stdout != 'Disabled'

- include_role:
    name: common_tasks
    tasks_from: flush_handlers.yml
