---
- name: Setup sysctl.conf
  template:
    src: "sysctl.conf.j2"
    dest: /etc/sysctl.conf
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: Reloaded Sysctl
  when: SYSCTL_SETTINGS is defined
