---
- name: Install python module for SELinux
  yum:
    name: "{{ item.name }}"
    state: installed
  with_items:
    - "{{ NAME_LIBSELINUX_PYTHON_MODULE }}"

- name: Get SELinux Status
  command: getenforce
  register: status_selinux
  changed_when: False
  failed_when: False
  become: True

- name: Disabled Selinux
  selinux:
    state: disabled
  become: True
  notify: Rebooted
  when:
    - not ansible_check_mode
    - status_selinux.stdout != 'Disabled'

- import_role:
    name: libraries
    tasks_from: flush_handlers.yml
