---
- name: Set Config
  template:
    src: mackerel-agent.conf.j2
    dest: /etc/mackerel-agent/mackerel-agent.conf
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: "{{ NAME_SERVICE_MANAGER }} restarted {{ NAME_DAEMON }}"
