---
- name: Remove Packages
  yum:
    name: "{{ item.NAME }}"
    state: "removed"
    enablerepo: "{{ item.ENABLEREPO | default([base]) }}"
  with_items:
    - "{{ COMMON_REMOVE_PACKAGES | default([]) }}"
    - "{{ COMMON_HOSTGROUP_REMOVE_PACKAGES | default([]) }}"
    - "{{ INVENTORY_REMOVE_PACKAGES | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_REMOVE_PACKAGES | default([]) }}"

- name: Install Packages
  yum:
    name: "{{ item.NAME }}"
    state: "installed"
    enablerepo: "{{ item.ENABLEREPO | default([base]) }}"
  with_items:
    - "{{ COMMON_INSTALL_PACKAGES | default([]) }}"
    - "{{ COMMON_HOSTGROUP_INSTALL_PACKAGES | default([]) }}"
    - "{{ INVENTORY_INSTALL_PACKAGES | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_INSTALL_PACKAGES | default([]) }}"
