---
- name: Disabled Selinux
  selinux:
    state: disabled

- name: Setup Hostname
  hostname:
    name: "{{ HOSTNAME }}"

- name: Setup sysctl.conf
  template:
    src: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.sysctl.conf.j2"
    dest: /etc/sysctl.conf
    mode: 0644
    owner: 0
    group: 0
  notify: Reload Sysctl

- name: Setup cron.d/sysstat
  template:
    src: "{{ ansible_os_family }}.sysstat.j2"
    dest: /etc/cron.d/sysstat
    mode: 0644
    owner: 0
    group: 0
