- name: User Create
  user:
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    home: "{{ item.home }}"
    shell: "{{ item.shell }}"
    uid: "{{ item.uid }}"
    create_home: "{{ item.create_home }}"
    state: present
