---
- name: Add the OS AND VERSION specific variables
  include_vars: "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"

- import_tasks: install.yml

- import_tasks: setup.yml
  when:
    - DOCKER_COMPOSE_SETTINGS is defined
    - DOCKER_COMPOSE_SETTINGS.SERVICES is defined
