---
#- name: install
#  dnf:
#    name: "{{ item }}"
#  with_items:
#    - "https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm"

- name: Docker install
  dnf:
    name: "{{ item }} --nobest"
  with_items:
    - containerd.io
    - docker-ce
    - docker-ce-cli
