---

- name: Get State repo
  stat:
    path: /etc/yum.repos.d/docker.io.repo
  register: stat_repo
  failed_when: False
  changed_when: False
  when:
    - not ansible_check_mode

- name: Add Repo
  command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when:
    - stat_repo.stat.exists

- name: Containerd.io install
  dnf:
    name: "containerd.io"

- name: Get Stat Docker Package
  command: rpm -q docker-ce
  register: stat_docker
  failed_when: False
  changed_when: False
  when:
    - not ansible_check_mode

- name: install docker-ce(--nobest)
  command: dnf install docker-ce --nobest -y
  when: stat_docker.rc == 1
