---
- name: Update check yum
  shell: yum check-update
  failed_when: false
  changed_when: false
#   register: check_update_result
#
# - name: Update yum
#   yum:
#     name: '*'
#     state: latest
#   when:
#     - not ansible_check_mode
#     - check_update_result.rc != 0
