---
- name: Check State "{{ daemon_name }}"
  command: "systemctl status {{ daemon_name }}"
  register: service_status
  changed_when: False
  failed_when: False
  tags:
    - skip-check

# Start if serivce stop(rc != 0)
- name: Restarted "{{ daemon_name }}"
  command: echo "Restarted(started) {{ daemon_name }}"
  when: service_status.rc != 0
  notify: Systemd started {{ daemon_name }}
  tags:
    - skip-check

# ReStart if serivce stop(rc == 0)
- name: Restarted "{{ daemon_name }}"
  command: echo "Restarted {{ daemon_name }}"
  when: service_status.rc == 0
  notify: Systemd restarted {{ daemon_name }}
  tags:
    - skip-check
