---
- name: Check State "{{ daemon_name }}"
  command: "service {{ daemon_name }} status"
  register: service_status
  changed_when: False
  failed_when: False
  tags:
    - skip-check

# Start if serivce stop(rc != 0)
- name: Restart "{{ daemon_name }}"
  command: echo "Restart(start) {{ daemon_name }}"
  when: service_status.rc != 0
  notify: Service start
  tags:
    - skip-check

# ReStart if serivce stop(rc == 0)
- name: Restart "{{ daemon_name }}"
  command: echo "Restart {{ daemon_name }}"
  when: service_status.rc == 0
  notify: Service restart
  tags:
    - skip-check
