---
- name: Check State "{{ daemon_name }}"
  command: "service {{ daemon_name }} status"
  register: service_status
  changed_when: False
  failed_when: False
  tags:
    - skip-check
    - service_start

- name: Start "{{ daemon_name }}"
  command: echo "Start {{ daemon_name }}"
  when: service_status.rc != 0
  notify: Service start
  tags:
    - skip-check
    - service_start
