---
- name: Check State "{{ daemon_name }}"
  command: "service {{ daemon_name }} status"
  register: service_status
  changed_when: False
  failed_when: False
  tags:
    - skip-check

# Start if serivce stop(rc != 0)
- name: Restarted "{{ daemon_name }}"
  command: echo "Restarted(started) {{ daemon_name }}"
  when: service_status.rc != 0
  notify: Service started
  tags:
    - skip-check

# ReStart if serivce stop(rc == 0)
- name: Restarted "{{ daemon_name }}"
  command: echo "Restarted {{ daemon_name }}"
  when: service_status.rc == 0
  notify: Service reloaded
  tags:
    - skip-check
