---
- name: Check State "{{ NAME_DAEMON }}"
  shell: systemctl status {{ NAME_DAEMON }}
  register: service_status
  changed_when: False
  failed_when: False
  ignore_errors: True
  when: not ansible_check_mode

# Start if serivce stop(rc != 0)
- name: Reloaded "{{ NAME_DAEMON }}"
  shell: echo "Restarted(started) {{ NAME_DAEMON }}"
  notify: "{{ NAME_SERVICE_MANAGER }} started {{ NAME_DAEMON }}"
  when:
    - not ansible_check_mode
    - service_status.rc != 0

# ReStart if serivce stop(rc == 0)
- name: Restarted "{{ NAME_DAEMON }}"
  shell: echo "Restarted {{ NAME_DAEMON }}"
  notify: "{{ NAME_SERVICE_MANAGER }} reloaded {{ NAME_DAEMON }}"
  when:
    - not ansible_check_mode
    - service_status.rc == 0
