---
- name: Check State "{{ NAME_DAEMON }}"
  shell: service {{ NAME_DAEMON }} status
  register: service_status
  changed_when: False
  failed_when: False
  ignore_errors: True
  when: not ansible_check_mode

- name: Started "{{ NAME_DAEMON }}"
  shell: echo "Started {{ NAME_DAEMON }}"
  notify: "{{ NAME_SERVICE_MANAGER }} started {{ NAME_DAEMON }}"
  when:
    - not ansible_check_mode
    - service_status.rc != 0
