- name: Server Reboot
  shell: "sleep 2 && reboot"
  async: 1
  poll: 0
  become: True
  listen: Rebooted
  when: not ansible_check_mode

- name: Wait for Reboot
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30
  become: False
  listen: Rebooted
  when: not ansible_check_mode

- name: Service restart network
  service:
    name: network
    state: restarted
  listen: Service restart network

- name: Update Grub
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  listen: Update Grub and Rebooted
  when: not ansible_check_mode

- name: Systemd restarted
  systemd:
    daemon-reexec: yes
  listen: Systemd restarted
  when: ansible_virtualization_type != 'docker'

- name: Cache clear yum
  command: yum clean all
  listen: Cache clear yum

- name: Update Server Certs
  command: update-ca-trust extract
