---
- name: Setup sshd_config
  template:
    src: sshd_config.{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.j2
    dest: /etc/ssh/sshd_config
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: "{{ NAME_SERVICE_MANAGER }} restarted {{ NAME_DAEMON }}"
