version: '3'

services:
   ansible:
    container_name: ansible-exec
    build: /opt/docker-compose-service/ansible/
    volumes:
      - /usr/local/git/ansible:/etc/ansible
      - /root/.ssh:/root/.ssh
    tty: true
